# Project information
site_name: Workspace Environment Management SDK v4.7 Documentation
site_title: Developer Docs
site_description: Workspace Environment Management SDK v4.7 Documentation

# Copyright
copyright: 'Copyright &copy; 1999-2019 Citrix Systems, Inc. All rights reserved. '

extra_css:
  - 'assets/stylesheets/extra.css'

# Configuration
theme:
  name: null
  custom_dir: devdocs-theme

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  feature:
    tabs: false
  palette:
    primary: white
    accent: blue
  font: false
  favicon: /media/favicon.ico
  logo: https://developer-docs.citrix.com/_static/Citrix_Logo_Black.png

# Customization
extra:
  social:
    - type: youtube
      link: https://www.youtube.com/channel/UCiOupk9QF6jdk3EDKTHDykA
    - type: github-alt
      link: https://github.com/citrix
    - type: twitter
      link: https://twitter.com/citrixdeveloper
    - type: linkedin
      link: https://www.linkedin.com/company/citrix/

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - footnotes
  - meta
  - extra

# Page tree
nav:
- Workspace Environment Management SDK:
    - Overview: index.md
    - Understanding the admin model: understanding-the-sdk.md
    - Getting started: getting-started-guide.md
- Workspace Environment Management SDK PowerShell Modules:
    - WEM.database.configuration: wem-posh-modules/configuration-database.md
    - WEM.infrastructure.service.configuration: wem-posh-modules/configuration-infrastructure-service.md
