# Project information
site_name: Citrix Workspace Environment Management SDK v4.7 Documentation
site_title: Developer Docs
site_description: Citrix Workspace Environment Management SDK v4.7 Documentation
site_url: https://developer-docs.citrix.com/

# Copyright
copyright: '&copy; 1999-2021 Citrix Systems, Inc. All rights reserved. '

# Feedback

issues_uri: https://github.com/citrix/devdocs-issue-collector/issues/new
assignees_uri:
  - kurtcoll
labels_uri:
  - documentation

extra_css:
  - 'assets/stylesheets/extra.css'
  - https://use.fontawesome.com/releases/v5.12.1/css/all.css

# Configuration
theme:
  name: null
  custom_dir: devdocs-theme
  
  # 404 page
  static_templates:
    - 404.html
  
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true
  
  # Default values, taken from mkdocs_theme.yml
  language: en

  palette:
    primary: teal
    accent: teal
  font: false
  favicon: https://docs.citrix.com/assets/images/favicon.ico
  logo: https://developer-docs.citrix.com/_static/logo.svg
  icon: fontawesome

extra:
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCiOupk9QF6jdk3EDKTHDykA
    - icon: fontawesome/brands/github-alt
      link: https://github.com/citrix
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/citrixdeveloper
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/citrix/

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

plugins:
  - search:
      separator: '[\s\-\.]+'
      prebuild_index: true

# Page tree
nav:
- Versions:
    - Latest: https://developer-docs.citrix.com/projects/workspace-environment-management-sdk/en/latest/
    - Citrix Workspace Environment Management 1912: https://developer-docs.citrix.com/projects/workspace-environment-management-sdk/en/1912/ 
- Workspace Environment Management SDK:
    - Overview: index.md
    - Understanding the admin model: understanding-the-sdk.md
    - Getting started: getting-started-guide.md
- Workspace Environment Management SDK PowerShell Modules:
    - WEM.database.configuration: wem-posh-modules/configuration-database.md
    - WEM.infrastructure.service.configuration: wem-posh-modules/configuration-infrastructure-service.md
